apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: juliocesarosorio709/eureka-server:latest
        name: eureka-server
        ports:
        - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-server
  type: LoadBalancer