apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-oauth
  template:
    metadata:
      labels:
        app: msvc-oauth
    spec:
      containers:
      - image: juliocesarosorio709/msvc-oauth:latest
        name: oauth-server
        ports:
        - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: msvc-oauth
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: msvc-oauth
  type: LoadBalancer