apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-api
  template:
    metadata:
      labels:
        app: rating-api
    spec:
      containers:
      - image: juliocesarosorio709/rating-api:latest
        name: rating-api
        ports:
        - containerPort: 2000
          name: port-rating-api

---
apiVersion: v1
kind: Service
metadata:
  name: rating-api
spec:
  ports:
  - port: 20
    protocol: TCP
    targetPort: port-rating-api
  selector:
    app: eureka-server
  type: LoadBalancer