apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth-server
  template:
    metadata:
      labels:
        app: oauth-server
    spec:
      containers:
      - image: juliocesarosorio709/oauth-server:latest
        name: oauth-server
        ports:
        - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: oauth-server
spec:
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: oauth-server
  type: LoadBalancer