apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-book-api
  template:
    metadata:
      labels:
        app: msvc-book-api
    spec:
      containers:
      - image: juliocesarosorio709/msvc-book-api:latest
        name: msvc-book-api
        ports:
        - containerPort: 1000
          name: port-book-api

---
apiVersion: v1
kind: Service
metadata:
  name: msvc-book-api
spec:
  ports:
  - port: 1000
    protocol: TCP
    targetPort: port-book-api
  selector:
    app: msvc-book-api
  type: LoadBalancer