version: '3.9'
services:

  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23.19
    ports:
      - "9411:9411"
    networks:
      - lan

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lan

networks:
  lan:
    name: lan