version: '3.9'
services:

  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23.19
    ports:
      - "9411:9411"
    networks:
      - lan

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lan

  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - lan
  
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - lan
  
  book-api:
    container_name: book-api
    build:
      context: ./book-api
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan

  rating-api:
    container_name: rating-api
    build:
      context: ./rating-api
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan

  msvc-usuarios:
    container_name: msvc-usuarios
    build:
      context: ./msvc-usuarios
      dockerfile: Dockerfile
    ports:
      - "7072:7072"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan
  
  oauth-server:
    container_name: oauth-server
    build:
      context: ./oauth-server
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    depends_on:
      - config-server
      - eureka-server
      - msvc-usuarios
    networks:
      - lan

  api-client:
    container_name: api-client
    build:
      context: ./api-client
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - eureka-server
      - rating-api
      - book-api
      - redis
    networks:
      - lan
  
  api-client-failover:
    container_name: api-client-failover
    build:
      context: ./api-client-failover
      dockerfile: Dockerfile
    depends_on:
      - config-server
      - eureka-server
      - rating-api
      - book-api
      - api-client
    networks:
      - lan
  
  gateway-server:
    container_name: gateway-server
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - eureka-server
      - rating-api
      - book-api
      - api-client
      - api-client-failover
      - msvc-usuarios
      - oauth-server
    networks:
      - lan


networks:
  lan:
    name: lan