apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: juliocesarosorio709/config-server:latest
        name: config-server
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  type: LoadBalancer