apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  selector:
    matchLabels:
      app: zipkin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
spec:
  selector:
    app: zipkin-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: LoadBalancer