apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-api-client-failover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-api-client-failover
  template:
    metadata:
      labels:
        app: msvc-api-client-failover
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup config-server; do echo waiting for config-server; sleep 2; done;']
      - name: wait-for-zipkin-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup zipkin-server; do echo waiting for zipkin-server; sleep 2; done;'] 
      containers:
      - image: juliocesarosorio709/msvc-api-client-failover:latest
        name: msvc-api-client-failover
        ports:
        - containerPort: 2003
        
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-api-client-failover
spec:
  ports:
  - port: 2003
    protocol: TCP
    targetPort: 2003
  selector:
    app: msvc-api-client-failover
  type: LoadBalancer