apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup config-server; do echo waiting for config-server; sleep 2; done;'] 
      - name: wait-for-zipkin-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup zipkin-server; do echo waiting for zipkin-server; sleep 2; done;'] 
      containers:
      - name: gateway-server
        image: juliocesarosorio709/gateway-server:latest
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer