version: '3.9'
services:

  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23.19
    ports:
      - "9411:9411"
    networks:
      - lan

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lan

  config-server:
    container_name: config-server
    image: juliocesarosorio709/config-server:latest
    # build:
    #   context: ./config-server
    #   dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - lan
  
  eureka-server:
    container_name: eureka-server
    image: juliocesarosorio709/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - lan
  
  book-api:
    container_name: book-api
    image: juliocesarosorio709/book-api:latest
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan

  rating-api:
    container_name: rating-api
    image: juliocesarosorio709/rating-api:latest
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan

  msvc-usuarios:
    container_name: msvc-usuarios
    image: juliocesarosorio709/msvc-usuarios:latest
    ports:
      - "7072:7072"
    depends_on:
      - config-server
      - eureka-server
    networks:
      - lan
  
  oauth-server:
    container_name: oauth-server
    image: juliocesarosorio709/oauth-server:latest
    ports:
      - "9100:9100"
    depends_on:
      - config-server
      - eureka-server
      - msvc-usuarios
    networks:
      - lan

  api-client:
    container_name: api-client
    image: juliocesarosorio709/api-client:latest
    environment:
      REDISADDRESS: redis://redis:6379
    depends_on:
      - config-server
      - eureka-server
      - book-api
      - rating-api
      - redis
    networks:
      - lan

  
  api-client-failover:
    container_name: api-client-failover
    image: juliocesarosorio709/api-client-failover
    depends_on:
      - config-server
      - eureka-server
      - rating-api
      - book-api
      - api-client
    networks:
      - lan
  
  gateway-server:
    container_name: gateway-server
    image: juliocesarosorio709/gateway-server:latest
    ports:
      - "8090:8090"
    networks:
      - lan

networks:
  lan:
    name: lan